/**
 * Log action constants
 * This file is safe to import in client-side code
 */
export const LogActions = {
  // Authentication
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SIGNUP: 'SIGNUP',
  GOOGLE_SIGNIN: 'GOOGLE_SIGNIN',
  
  // Expenses
  EXPENSE_CREATE: 'EXPENSE_CREATE',
  EXPENSE_UPDATE: 'EXPENSE_UPDATE',
  EXPENSE_DELETE: 'EXPENSE_DELETE',
  
  // Budgets
  BUDGET_SET: 'BUDGET_SET',
  BUDGET_UPDATE: 'BUDGET_UPDATE',
  BUDGET_DELETE: 'BUDGET_DELETE',
  
  // Income
  INCOME_CREATE: 'INCOME_CREATE',
  INCOME_UPDATE: 'INCOME_UPDATE',
  INCOME_DELETE: 'INCOME_DELETE',
  
  // Categories
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',
  
  // User Profile
  PROFILE_UPDATE: 'PROFILE_UPDATE',
  AVATAR_UPLOAD: 'AVATAR_UPLOAD',
  CURRENCY_CHANGE: 'CURRENCY_CHANGE',
  
  // AI Recommendations
  AI_RECOMMENDATION_GENERATE: 'AI_RECOMMENDATION_GENERATE',
  AI_RECOMMENDATION_SAVE: 'AI_RECOMMENDATION_SAVE',
  AI_RECOMMENDATION_DELETE: 'AI_RECOMMENDATION_DELETE',
  
  // Settings
  SETTINGS_VIEW: 'SETTINGS_VIEW',
  LOGS_VIEW: 'LOGS_VIEW',
  
  // View actions
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
} as const;

